### PR TITLE
Add <FluentNumberField>

### PR DESCRIPTION
**Pull request by vnbaaij**
# Pull Request

## 📖 Description
This PR adds a `<FluentNumberField>` component to wrap the <fluent-number-field> component 
### 🎫 Issues
#48,
#39 
Bug in FAST (https://github.com/microsoft/fast/issues/4776) affects this component as well.

## 👩‍💻 Reviewer Notes
Besides the component itself (`FluentNumberField.razor`), pages have been added and modified to test the component. These are `FluentNumberFieldTest`, `ComponentBindings` and `RawBindings`

### General

- [x] I have added tests for my changes.
- [x] I have tested my changes.
- [x] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [x] I have added a new component
- [ ] I have modified an existing component

## ⏭ Next Steps
Work needs to be done on the binding of values related to the up/down buttons. Seems `onchange` events are not triggered by those.
The precision in the Javascript is limited to 12 digits. When using a .NET `long` the MinValue and MaxValue are longer than 12 digits. Is it possible to change this in the script?

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks @vnbaaij ! This will be a great contribution. I noticed there was an issue with the implicit bind. I think you need to add some configuration here: https://github.com/microsoft/fast-blazor/blob/main/src/Microsoft.Fast.Components.FluentUI/BindAttributes.cs Can you give that a try and see if that fixes the issue?

**Comment by vnbaaij** [comment]
I added the configuration. This did indeed fix the implicit bind. It doesn't fix that up/down do not fire `onchange` though.

**Comment by EisenbergEffect** [comment]
The buttons fire an `oninput` event. `onchange` is fired on blur only I believe while `oninput` is fired on all input (key, button press, etc.). Here's the commit that fixed the underlying issue which did exists: https://github.com/microsoft/fast/commit/66bcd958ae59e56618631af50020d7234bb7a2e2

**Comment by vnbaaij** [comment]
So how would we be able to connect these specific `oninput` events to the value? Do we need to add more configuration to the BindAttributes file?

**Comment by EisenbergEffect** [comment]
Let's ask @SteveSandersonMS for help on this one. There may be a way to configure things better. Perhaps this is just a case where the event override need to be used when binding? Or should input be the default event?

**Comment by SteveSandersonMS** [comment]
You can configure `@bind` to use whatever default event name you want, but it does have to be one specific event. It would be most normal to use `change` so that an update doesn't fire on each keystroke unless the developer specifically opts into that by putting `@bind:event="oninput"` on the element.

For `<input type="number">` we use the `change` event, and the standard DOM element does fire a `change` when you click its up/down buttons. I would have expected a `<fluent-number-field>` to behave like `<input type="number">` in terms of which events it raises.

**Comment by EisenbergEffect** [comment]
Thanks Steve!

Pinging @robarbms who worked on this component, as there may be a bug as well if we're not matching the native component's event patterns.

**Comment by EisenbergEffect** [comment]
Pinging @robarbms to check on the event patterns.

**Comment by EisenbergEffect** [comment]
@vnbaaij Can you update this PR to use the `change` event and then we'll get it merged in. Thanks!

**Comment by vnbaaij** [comment]
@EisenbergEffect done!

**Comment by EisenbergEffect** [comment]
Awesome. Adding to my queue for final review. Thanks!

**Comment by robarbms** [comment]
Weird, I did not get this thread when you added me. I have a fix for this in the FAST library that's waiting on reviews. [PR 4881](https://github.com/microsoft/fast/pull/4881/files)

This fix will fire input and change when changing the value through the text box or using the increment or decrement buttons.

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
Thanks @robarbms ! I reviewed and approved the other PR, so hopefully we can get that in shortly.

@vnbaaij This looks good. Thanks also for updating the examples. @nicholasrice Can you do a second review of this? I'd like to get this in and then do the 2.0 fixup work.

**Review by nicholasrice — APPROVED** [review]

**Review by EisenbergEffect — APPROVED** [review]

**Pull request merged**
