### PR TITLE
FluentButton and FluentCalendar tests

### PR DESCRIPTION
**Pull request by Andras-Csanyi**
# Pull Request

## 📖 Description

bUnit tests against FluentButton and FluentCalendar components.
The tests check the HTML output of the components

### 🎫 Issues

- no relevant issue

## 👩‍💻 Reviewer Notes

- in case of both components the extras provided by FluentComponentBase are checked
- attributes are covered, in case of string null, empty and whitespace is checked
- in case of enum input all enum value is exercised
- in case of FluentCalendar the Month input is not validated, so I added a tests where `13` is the input to show that there is no validation here. I assume there are people checking the tests to understand how component works.
- [the xml doc of the button form target](https://github.com/microsoft/fast-blazor/blob/3f3b741b7602adb9c7ca67d762f86991eacb46bf/src/Microsoft.Fast.Components.FluentUI/Components/Button/FluentButton.razor.cs#L47) determines valid values, but no validation.
- as for the two validation above, is there a plan to add validation there?

## 📑 Test Plan

- N/A

### General

- [ ] I have added tests for my changes.
- [ ] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [ ] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component

### CODE REVIEW

**Comment by vnbaaij** [comment]
Love it! Will take a better look later today or tomorrow. Thanks.

**Comment by vnbaaij** [comment]
> * in case of FluentCalendar the Month input is not validated, so I added a tests where `13` is the input to show that there is no validation here. I assume there are people checking the tests to understand how component works.
> * [the xml doc of the button form target](https://github.com/microsoft/fast-blazor/blob/3f3b741b7602adb9c7ca67d762f86991eacb46bf/src/Microsoft.Fast.Components.FluentUI/Components/Button/FluentButton.razor.cs#L47) determines valid values, but no validation.
> * as for the two validation above, is there a plan to add validation there?
I'll add validation for both of there (in OnParameterSet)

**Comment by vnbaaij** [comment]
Hi @Andras-Csanyi,

Do you need to change anything in this PR now that I've included the validations? If not, I can merge it in later today and push a new release.

**Comment by Andras-Csanyi** [comment]
> Hi @Andras-Csanyi,
> 
> Do you need to change anything in this PR now that I've included the validations? If not, I can merge it in later today and push a new release.

Let me double check the code in the afternoon and I'll get back to you. One test should be failing if the validation throws exception and I need to align the test case accordingly. I'll be back in late afternoon.

**Comment by Andras-Csanyi** [comment]
@vnbaaij the tests are fixed. In case of Calendar Month I added BVA and EP tests, while for Target string.empty and some funky value is checked as negative, while all accepted value is exercised as input. From my point of view the PR can be merged if you are ok with it.

**Pull request merged**
