### PR TITLE
(feature) Generics for FluentSelect, FluentListbox and FluentCombobox

### PR DESCRIPTION
**Pull request by vnbaaij**
# Pull Request

## 📖 Description

Make FluentSelect, FluentListbox and FluentCombobox generic. Also added functionality to make them work with a (generic) `Option` list

You can now do:
```
<h2>From list of string items</h2>
<FluentSelect Items=@options  />

<h2>From list of int items</h2>
<FluentSelect Items=@options2 />

@code{
     List<Option<string>> options = new()
    {
            { new Option<string> { Key = "1", Value = "One" }},
            { new Option<string> { Key = "2", Value = "Two", Selected = true }},
            { new Option<string> { Key = "3", Value = "Three" }}

    };

    List<Option<int>> options2 = new()
    {
            { new Option<int> { Key = 1, Value = 1, Disabled = true }},
            { new Option<int> { Key = 2, Value = 2 }},
            { new Option<int> { Key = 3, Value = 3 }}

    };
}
```

### 🎫 Issues
If you manually supply the options, you now need to explicitly cast a value as a string (`@("...")`) 
```
<FluentSelect Appearance="Appearance.Filled" @bind-Value="@selectValue">
    <FluentOption>This option has no value</FluentOption>
    <FluentOption Disabled="true">This option is disabled</FluentOption>
    <FluentOption Value="@("hi")">This option has a value</FluentOption>
    <FluentOption Selected="true">This option is selected by default</FluentOption>
</FluentSelect>
```

### General

- [X] I have added tests for my changes.
- [X] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [X] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [X] I have modified an existing component

## ⏭ Next Steps

If we want to change it to work like this, all the sample pages and the componentbindings page need to be reworked (not hard)

### CODE REVIEW

**Comment by awentzel** [comment]
@vnbaaij would this be for the .NET 6.0 release or for a future release?

**Comment by vnbaaij** [comment]
Future release. I would like to have Javier or someone else take a look at it first

**Review by nicholasrice — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
I'm feeling uncomfortable about bringing this in at the last minute. Let's get more feedback and consider this for a future release.

**Comment by awentzel** [comment]
Hi @vnbaaij, What's the status on this PR? Still a work in progress?  We're doing a publish soon so would be great to get some of these PRs merged.  Cheers,

**Review by awentzel — APPROVED** [review]

**Comment by vnbaaij** [comment]
> Hi @vnbaaij, What's the status on this PR? Still a work in progress? We're doing a publish soon so would be great to get some of these PRs merged. Cheers,

As far as I'm concerned this is good to go!

**Pull request merged**
