### PR TITLE
Fix ToString for other culture

### PR DESCRIPTION
**Pull request by ehsangfl**
on some cultures, default tostring method has an issue for numeric types. so I changed it to use Invariant culture

### CODE REVIEW

**Comment by vnbaaij** [comment]
Can you elaborate on what kind of issues you are referring to?

**Comment by ehsangfl** [comment]
it is UI issue. the bottom property of  PresenceBadge does not setted correctly on some cultures

**Comment by vnbaaij** [comment]
Can you post a screenshot please?

**Comment by ehsangfl** [comment]
after

**Comment by vnbaaij** [comment]
If I go to this page: https://brave-cliff-0c0c93310-233.centralus.azurestaticapps.net/Lab/PresenceBadge and set the direction to 'rtl', the `PresenceBadge`s are displayed in the correct spot, correct?

From the image it seems like you are using the `PresenceBadge` in a way it is not supposed to be used. It is supposed to show if a user is online, away, etc. It seems you are trying to use it inside a button. Try it the other way around, i.e. use the button inside of the `PresenceBadge`:

```
<PresenceBadge>
    <FluentButton>...</FluentButton>
</PresenceBadge>
```

And see how that renders.

**Review by vnbaaij — APPROVED** [review]

**Pull request merged**
