### PR TITLE
feat: Add FluentIcon component

### PR DESCRIPTION
**Pull request by vnbaaij**
# Pull Request

## 📖 Description

This PR adds the `<FluentIcon>` component and supporting code. The component offers an on-demand loading icons from the [FluentUI System Icons set](https://github.com/microsoft/fluentui-system-icons). Some highlights:
- Not using fonts! Uses SVGs as the source and display the icon as real SVG (not  with SVG src)
- Contains all the 11k+ FluentUI System Icons
- Downloads the SVGs on demand (and browser caches them) 
- Uses C# Source generator to create all the constants from fluentui-system-icons repo
- Can use Accent Fill color (still need to look at specifying your own color)
- Comes with a demo page that allows searching through all of the icons (by name, size and variant) 
- Supports slots (see the search button on the search page
- Add an IconService and ServiceCollection extensions so same component can be used in both Server and WebAssembly sites

## 👩‍💻 Reviewer Notes

Look at IconPage for usage patterns and 

### General

- [X] I have added tests for my changes.
- [X] I have tested my changes.
- [X] I have updated the project documentation to reflect my changes.
- [X] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [X] I have added a new component
- [ ] I have modified an existing component

## ⏭ Next Steps

Update templates to use `builder.Services.AddFluentUIComponents()` and `builder.Services.AddHttpClient();` for Server app

### CODE REVIEW

**Comment by GurliGebis** [comment]
Would it be possible to have the icons included, as an option, to be able to use it internally on machines without internet access?

**Comment by vnbaaij** [comment]
> Would it be possible to have the icons included, as an option, to be able to use it internally on machines without internet access?

The icons are included in the DLL and are downloaded from the server when needed. There is always a server involved so even without internet access, this will still work.

**Review by EisenbergEffect — APPROVED** [review]

**Comment by JeepNL** [comment]
> The icons are included in the DLL and are downloaded from the server when needed. There is always a server involved so even without internet access, this will still work.

Does this mean a Blazor WASM client downloads all 11k+ FluentUI System Icons? (It downloads all dll's it needs)

**Comment by vnbaaij** [comment]
> Does this mean a Blazor WASM client downloads all 11k+ FluentUI System Icons? (It downloads all dll's it needs)

No, contents of the wwwroot folder in an RCL are treated like ordinary static files on the server. They don’t get downloaded until requested.

**Comment by JeepNL** [comment]
@vnbaaij Great and I just want to say I'm very interested in using fast-blazor and now there's a Nuget template to get started with it I know I'm going to try it out again (for real this time, because now there's  more info how to use it). I really like the clean (that's what I call it) design and more and more components added to it over time. I think this is a great project, and I would love to see the default Blazor templates using it instead of Bootstrap. But that's just my opinion. I think Blazor and 'Fast-Blazor' are made for each other :)

**Pull request merged**
