### PR TITLE
Extend Datagrid  #263

### PR DESCRIPTION
**Pull request by ehsangfl**
Extended the datagrid component as described in #263

### CODE REVIEW

**Comment by vnbaaij** [comment]
There are a lot of great things in this! Like I said in #263, I'm not sure if we want to take in all of it. Would it make sense to isolate changes and create some smaller PRs?
Some remarks on the current state::
1) We do not work with `#regions` in source files in this repo. Please remove them
2) We do not use `Nullable<...>`, Just use `...?` please
3) Please pull in the latest changes from main
4) Can you look at the conflicts that are there now. I made some modifications to the grid already.
5) Like the idea of the column types. Think prefixing them with DataGrid is a bit overkill. Also, please use the names of the corresponding Fluent components (Textbox->TextField)
6) Is a Combobox really what you would use in a grid? I would think in most cases you want the user to pick a predefined value from a set list and not let them type one themselves (i.e. use a `FluentSelect`)(or offer both)
7) The commit history looks a bit like a mess. Any way you can clean that up a bit?

**Comment by ehsangfl** [comment]
I will create 4 PR
1- generate headers, by `Display` attr
2- new sorting ability
3- embedded filters
4- Inline datagrid editor
is it ok?

**Comment by vnbaaij** [comment]
Sounds good!

One other thing I thought of (sorry, don't want to sound too critical. Just want to make sure we do the 'right things'). For the enums I am using the `System.ComponentModel.Description` attribute. Can you use that as well for the Display? So we can keep it consistent.

**Comment by ehsangfl** [comment]
np. feel free to give tips

**Pull request closed without merging**
