### PR TITLE
(feature) Project templates

### PR DESCRIPTION
**Pull request by vnbaaij**
# Pull Request

## 📖 Description

This PR adds templates to the toolkit that allow you to start a new Blazor Server or Blazor WebAssembly project with all the needed changes to use the Fluent UI component library already in place

### 🎫 Issues
Addresses #88 

## 👩‍💻 Reviewer Notes
When merging this in, we need to update the general readme to point to these templates and describe how to set them up

## 📑 Test Plan
Go through provided readme and see if steps needed are clear.

### General

- [ ] I have added tests for my changes.
- [X] I have tested my changes.
- [X] I have updated the project documentation to reflect my changes.
- [X] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

## ⏭ Next Steps
Once the PR #142 is merged in we need to update the templates and generate/upload new NuGet packages (instructions provided in `templates/readme.md`

### CODE REVIEW

**Review by EisenbergEffect — APPROVED** [review]
I like this. A couple of questions:

* Should we simplify the started templates or do you feel it's necessary to have such a "full" starter kit?
* Should we change the package name to maybe be something more like `Microsoft.Fast.Templates.FluentUI.BlazorWebAssembly`?
* Do we need to do anything with our publish process to ensure these additional packages get published?

**Comment by vnbaaij** [comment]
> I like this. A couple of questions:
> 
> * Should we simplify the started templates or do you feel it's necessary to have such a "full" starter kit?

Can you elaborate? The templates are a 'translation' of what you get when you do 'File->New' for a Blazor project

> * Should we change the package name to maybe be something more like `Microsoft.Fast.Templates.FluentUI.BlazorWebAssembly`?

Yes! I'll add this in a new commit to this PR

> * Do we need to do anything with our publish process to ensure these additional packages get published?

I'll look into that

**Comment by EisenbergEffect** [comment]
> > I like this. A couple of questions:
> > 
> > * Should we simplify the started templates or do you feel it's necessary to have such a "full" starter kit?
> 
> Can you elaborate? The templates are a 'translation' of what you get when you do 'File->New' for a Blazor project
> 
> > * Should we change the package name to maybe be something more like `Microsoft.Fast.Templates.FluentUI.BlazorWebAssembly`?
> 
> Yes! I'll add this in a new commit to this PR
> 
> > * Do we need to do anything with our publish process to ensure these additional packages get published?
> 
> I'll look into that

For the template content, if that's the same as `File->New` Blazor then let's leave that as is. We want it to feel familiar for Blazor devs as much as possible.

Thanks @vnbaaij !

**Comment by vnbaaij** [comment]
> * Do we need to do anything with our publish process to ensure these additional packages get published?

The packages only need to be re-created when the template sources are changed/updated. This is a manual step (see the `readme` file in the `\templates` folder). After that they need to be uploaded to NuGet. I'm not sure how much of that can be automated and if it is worth the hassle.

With my latest changes the latest stable version in the 1.* range of the Fluent UI package should be installed when creating a project. This further reduce the need to update the templates frequently. 

The generated NuGet template packages are included in the `\templates` folder. Once tested and approved they can be made available on NuGet. Instructions on how to install, use and uninstall are in the the `readme` file in the `\templates` folder

**Comment by vnbaaij** [comment]
Result in VS after installing templates:
image

Result in browser after using Server template:
image

**Comment by EisenbergEffect** [comment]
@awentzel Can you take a look at this when you get a chance? This PR will add two new packages that we'd want to publish, which enable starter templates through Visual Studio and the CLI. I wasn't sure if our publish pipeline and steps would handle multiple packages or if we needed to modify things.

**Comment by awentzel** [comment]
> @awentzel Can you take a look at this when you get a chance? This PR will add two new packages that we'd want to publish, which enable starter templates through Visual Studio and the CLI. I wasn't sure if our publish pipeline and steps would handle multiple packages or if we needed to modify things.

@EisenbergEffect I'll investigate, as I unclear as well.

**Comment by vnbaaij** [comment]
@awentzel let me know if you want to do a call on this to let me explain the details

**Review by awentzel — APPROVED** [review]

**Pull request merged**
