### PR TITLE
Fluent accordion item b unit tests

### PR DESCRIPTION
**Pull request by Andras-Csanyi**
# Pull Request

## 📖 Description
Following up [this](https://github.com/microsoft/fast-blazor/discussions/249) conversation by this PR. In more details about what is in this PR:

- `global.json` is added to `.gitignore`, I have multiple .NET Core SDK on my machine and Rider automatically creates this file. It might be confusing or disturbing for others.
- I added [bUnit](https://bunit.dev/) tests agains `FluentAccordionItem`, these tests checking whether the rendered/generated HTML is correct or not
- I added [bUnit](https://bunit.dev/) tests agains `FluentAccordion`, these tests checking whether the rendered/generated HTML is correct or not
- tests are covering the component's parameters (`Expanded` for example) and covering parameters coming from component base (unmatched parameters, style and css class)
- tests are also covering default values, e.g. `Expanded`
- #261 is an interesting case coming from this testing

### 🎫 Issues

No issue related to this topic to my knowledge.

## 👩‍💻 Reviewer Notes

- bUnit makes possible to check behaviors of components fully or partially and these can be provided later
- by this PR I'd like to establish naming standards and what test project looks like, in these topics I'm looking for feedback and/or guidance
- the test project itself doesn't make distinction between `net6.0` and `net7.0` targets. The whole solution compiles properly with `dotnet build`, but when I try to compile it `dotnet build -f net6.0/net7.0` the Generators project fails by saying that these targets aren't defined there. So, I left the test project with `<TargetFrameworks>net6.0;net7.0</TargetFrameworks>` only. I need some guidance here if I did something not enough here.
- I haven't added any attributes related to excluding tests from code coverage, do we plan to introduce code coverage checking? If so, what is the guidance here? I used SonarCloud before.

## 📑 Test Plan

- render tests against `FluentAccordionItem` checking whether the generated HTML is correct or not
- render tests against `FluentAccordion` checking whether the generated HTML is correct or not

### General

- [ ] I have added tests for my changes.
- [x] I have tested my changes.
- [ ] I have updated the project documentation to reflect my changes.
- [x] I have read the [CONTRIBUTING](https://github.com/Microsoft/fast-blazor/blob/master/CONTRIBUTING.md) documentation and followed the [standards](https://www.fast.design/docs/community/code-of-conduct/#our-standards) for this project.

### Component-specific

- [ ] I have added a new component
- [ ] I have modified an existing component

## ⏭ Next Steps

Once we agreed on project structure and test naming guidelines I'm planning to provide the render tests against the remaining components, and introducing tests checking component behaviors as much as bUnit makes it possible.

### CODE REVIEW

**Comment by Andras-Csanyi** [comment]
@microsoft-github-policy-service agree

**Comment by Andras-Csanyi** [comment]
Hi,

Sounds good to me for waiting for FAST folks to formulate their viewpoint. Once we have a strategy or similar, I'm happy to contribute.

I believe the advantage of bUnit is that it doesn't require any environment or browser (headless or not). It seems a good portion of the logic can be tested and the tests are fast. However, the real test is running in a browser. If I would be a project owner I would expect bUnit tests (fast checks on component and/or widget level) and E2E tests to check the business logic (whatever it means in the given context). This was my 2 cents... let's wait for FAST folks. :)

**Comment by Andras-Csanyi** [comment]
@vnbaaij Did you have the chance to catch up FAST folks?
In the meantime I'll refresh the PR in the following days.

**Review by EisenbergEffect — APPROVED** [review]

**Comment by EisenbergEffect** [comment]
@Andras-Csanyi Thanks for the awesome PR and the great write-up. I really appreciate the notes.

This looks good to me. I think having some basic tests to assert the correct output of the Blazor components makes a lot of sense. Any deeper tests can be handled directly in FAST with Playwright. There's really two different scenarios so two different types of tests makes sense.

@vnbaaij I'll let you take it from here. Thanks!

**Comment by Andras-Csanyi** [comment]
@vnbaaij I updated the PR and added further tests covering FluentAccordion.
This PR is ready for review, and I'm looking forward to read your feedback.

**Comment by vnbaaij** [comment]
I looked at the test and project and think it is good to go! Can you fix the conflict mentioned? I can merge it after that.

**Comment by vnbaaij** [comment]
Thanks again for your contribution. Hope you will be supplying more tests soon!

**Pull request merged**
